version: "3.8"
services:
  enid_bot:
    build: .
    image: 'enid_bot:1'
    container_name: 'enid_bot'
    command:
      sh -c "cd src && 
             poetry run watchmedo auto-restart --directory=. --recursive -- python main.py"
    env_file: .env
    volumes:
      - ./src:/service/src
      - ./tests:/service/tests
    networks:
      - backend
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: 'chrome'
    environment:
      - SE_OVERRIDE_MAX_SESSIONS=true
      - SE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - backend
    ports:
      - '4444:4444'
      - '7900:7900'
    privileged: true
    shm_size: 2g
    restart: unless-stopped

networks:
  backend:
